### ISSUE TITLE
Missing Stream

### ISSUE THREAD

**Issue by etherwrangler** [secdoc/Graylog_Pipeline#1]
I found your Pipeline config and it looks like there's a stream missing for the naxsi_reverse_proxy pipeline.  When importing there's an error about a missing Entity for UID 13d566d0-4c4c-42da-9237-9832a5e7be44.  I got around it by just removing that pipeline since I don't use nginx but figured I'd point this out to you.

**Comment by secdoc** [comment]
> I found your Pipeline config and it looks like there's a stream missing for the naxsi_reverse_proxy pipeline. When importing there's an error about a missing Entity for UID 13d566d0-4c4c-42da-9237-9832a5e7be44. I got around it by just removing that pipeline since I don't use nginx but figured I'd point this out to you.

Thank you...That is because I am not using it within my current config. The Input is there, because I vacillate between using it from time to time, but it is there so you can use the pipeline and create the stream based on your configuration/needs.

**Comment by secdoc** [comment]
See comment above.
